### ISSUE TITLE
GitHub sync

### ISSUE THREAD

**Issue by jubalh** [gschwind/page#3]
On http://www.hzog.net/index.php/Downloads one can see 1.9.4 and 1.9.6 on GitHub there is 1.9.3 the latest tag/release. Are you keeping GitHub up to date still? :-) Just wondering to where to get latest release from.

regards,
jubalh

**Comment by jubalh** [comment]
Ah it seems you are in sync but just did push without --tags :)

**Comment by gschwind** [comment]
Yes I only forgive tags quite often, the git is the main repository and is always up-to-date (without my own local branch)

Best regards

**Comment by jubalh** [comment]
Thanks!
